# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_installed_dependencies": "00_dependency_checker.ipynb",
         "check_new_version": "00_dependency_checker.ipynb"}

modules = ["checker.py"]

doc_url = "https://muellerzr.github.io/dependency_checker/"

git_url = "https://github.com/muellerzr/dependency_checker/tree/master/"

def custom_doc_links(name): return None
